// Objective-C API for talking to test Go package.
//   gobind -lang=objc test
//
// File is generated by gobind. Do not edit.

#ifndef __Test_H__
#define __Test_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT void TestShowMessage(NSString* messageText);

#endif
